"""update log table structure

Revision ID: 6b23ccda4f81
Revises: 7b56fcf9f9f2
Create Date: 2025-04-18 17:28:32.214490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b23ccda4f81'
down_revision: Union[str, None] = '7b56fcf9f9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('logs', sa.Column('token', sa.String(), nullable=False))
    op.add_column('logs', sa.Column('environment', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('device', sa.JSON(), nullable=True))
    op.add_column('logs', sa.Column('error', sa.JSON(), nullable=True))
    op.add_column('logs', sa.Column('custom', sa.JSON(), nullable=True))
    op.drop_column('logs', 'error_name')
    op.drop_column('logs', 'created_at')
    op.drop_column('logs', 'custom_metadata')
    op.drop_column('logs', 'error_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('error_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('custom_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('error_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('logs', 'custom')
    op.drop_column('logs', 'error')
    op.drop_column('logs', 'device')
    op.drop_column('logs', 'environment')
    op.drop_column('logs', 'token')
    op.drop_column('logs', 'timestamp')
    # ### end Alembic commands ###
